[IMP] runtime: improve call stack in errors
In this commit, we reduce the number of frames in errors, to make it
easier to understand. We also add a named wrapper function for lifecycle
hooks so we can have the important context when debugging. An error
could look like this now:

```
OwlError: [Owl] Unhandled error. Destroying the root component
    at finalize (owl.js:2026:30)
    at Array.<anonymous> (owl.js:5981:32)
    at handleError (owl.js:2041:37)
    at MountFiber.complete (owl.js:2317:13)
    at Scheduler.processTasks (owl.js:5882:27)
    at owl.js:5853:64
Caused by: Error: boom
    at ProductCard.<anonymous> (543e3ccd-78ac-4a27-9132-94af59b65ed1:9:19)
    at ProductCard.onMounted (owl.js:6067:26)
    at MountFiber.complete (owl.js:2311:25)
    at Scheduler.processTasks (owl.js:5882:27)
    at owl.js:5853:64
```